
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert([
        {category_id: "1", name: "Hex-bells",  img: "https://www.roguefitness.com/media/catalog/product/cache/1/rogue_header_2015/472321edac810f9b2465a359d8cdc0b5/r/o/rogue-dumbbells-h.jpg", price: 880.00, description: "Sold in sets of 5lbs - 80lbs only. 6 sided and Rubber. Multi-purpose.", rating: 4, stats: "Hex-bells are sold in pairs and available in weights ranging from 2.5LB to LB. This standard rubber hex design is a great, budget-priced option that still delivers on quality, performance, and longevity. The heavy-duty, rubber-encased heads minimize noise and limit wear and tear (to both the bells and your flooring), while the chrome-plated handle is ergonomically designed for a firm but comfortable feel in any grip style. All smaller Hex-bells up to 10LB feature a 25MM diameter handle, while those 12.5LB and up have a larger 35MM diameter handle"},
        {category_id: "1", name: "Urethane-bells",  img: "https://www.thegymrevolution.co.uk/media/catalog/product/cache/1/image/800x800/9df78eab33525d08d6e5fb8d27136e95/p/u/pud-atx-atmo-03_1.jpg", price: 1900.00, description: "Sold in sets of 5lbs - 80lbs only. Circular urethane dumbbells, multi-purpose.", rating: 5, stats: "Urethane Dumbbells are sold in pairs and available in 5LB increments up to 80LB. As an alternative to traditional rubberized bells, this design features solid steel heads with a durable, shock-absorbent urethane plating, fully over-molded to the center. The heads are welded to a 6 straight hardened chrome handle to create a solid, single-piece dumbbell that moves fluidly and compactly and won’t damage your flooring on a drop."},
        {category_id: "2", name: "Silver Barbell",  img: "https://cdn.shopify.com/s/files/1/1950/1891/products/ob1500_1_3cd57b95-788e-4f4c-b4dc-87898cf1c814_700x.jpg?v=1521423277", price: 150.00, description: "Extreme grip, 45lb FIT barbell.", rating: 5, stats: "The new stainless steel version of our 20KG Rogue Ohio Bar is machined and assembled in Columbus, Ohio, and features a 200,000 PSI tensile strength shaft, chrome sleeves, and an exclusive knurl pattern that’s 100% in its original, machined form for an unmatched feel. With quality composite bushings and dual knurl marks, the Stainless Steel Ohio Bar is optimized for both Olympic lifts and Powerlifting—delivering a firm but non-abrasive grip, a consistent spin, and a unique balance of whip and rigidity."},
        {category_id: "3", name: "Wall Mount",  img: "https://images-na.ssl-images-amazon.com/images/I/31-738icoQL._SX425_.jpg", price: 500.00, description: "Easy mount, durable, and folds up to keep out of your way when not in use!", rating: 4, stats: "The goal with the Wall Mount was to develop a wall-mount unit that could be folded inward or outward for space efficiency, yet still offer the sturdiness of our standard R-Series racks. To achieve this, our engineering team developed a unique hinge-and-pin system that is both easy to install and rock solid. In use as a squat stand, pull-up rig, or power rack, the feel is miles beyond lighter fold-back setups that use thinner steel."},
        {category_id: "3", name: "Power Rack - 390c",  img: "https://www.roguefitness.com/media/catalog/product/cache/1/image/1500x1500/472321edac810f9b2465a359d8cdc0b5/r/m/rml-390-web-2.jpg", price: 915.00, description: "Squat rack with safety support.", rating: 5, stats: "With an interior depth of 24 inches or 30 inches, the Power-390C is an all-in-one power rack that can improve the efficiency of a small garage gym or major weight training center. With 0.625 hardware and Westside hole spacing, it also provides an appealing middle ground between the Rogue Monster and Series power racks. Easy to set-up and install out the box, this rack comes standard with a pair of Monster Lite J-cups, a pin/pipe safety set, four band pegs, and a 43 inch Fat/Skinny Pull-Up Bar."},
        {category_id: "3", name: "Power Rack - 690c",  img: "https://www.roguefitness.com/media/catalog/product/cache/1/image/1500x1500/472321edac810f9b2465a359d8cdc0b5/r/m/rml-690-web4.jpg", price: 1400.00, description: "Squat rack with safety support, and plate racks.", rating: 5, stats: "We’ve designed the RML-690C with full compatibility across the Monster Lite line, making it among the most durable and customizable power racks on the market. The unit’s 3x3 11 gauge steel, Westside Hole Spacing uprights in your choice of 10 custom semi gloss powdercoats feature Westside hole spacing, with the same 0.625 bolts and fasteners as our Infinity Series. A pair of Monster Lite J-Cups, pin/pipe safeties, and a four-pack of band pegs are included standard, as are eight convenient bumper plate storage posts. The Power-690C set-up also comes with both the 43 inch Single Skinny Pull-Up Bar & 43 inch Beam with FIT nameplate."},
        {category_id: "4", name: "Flat Bench",  img: "https://lifefitness.com/product-photos/6521/frame_color:7016,upholstery_color:7126/", price: 200.00, description: "Multi-purpose Flat Bench!, optimize your workouts!", rating: 4, stats: "Ergonomically designed and built in the USA, the Flat Bench ships fully assembled and offers a needed antidote to the wobbly flat benches and unwieldy FID weight benches routinely imported by the big box stores. While easy to maneuver at just 40 pounds, the Flat Utility Bench is also heavy-duty enough for a tank to sit on it. So no matter the size of the athlete or the intensity of the workout, you've got a rock solid foundation underneath you."},
        {category_id: "4", name: "Flat / Incline bench",  img: "https://www.adamantbarbell.com/1493-thickbox_default/york-sts-flat-incline-bench.jpg", price: 300.00, description: "Multi-purpose adjustable Bench, optimize your workouts!", rating: 5, stats: "With more than 50 combinations of seat and back-rest positions to choose from, the adjustable Bench can easily adapt to each individual athlete, improving the overall efficiency and productivity of any strength training facility. No matter your size, workout preferences, or available training space, this compact, 11-gauge steel bench provides the rare combination of sturdiness and maneuverability that few other adjustable weight benches even attempt to match"},
        {category_id: "4", name: "Flat / Incline / Decline Bench",  img: "https://images-na.ssl-images-amazon.com/images/I/61jM%2B06jD4L._SX425_.jpg", price: 600.00, description: "Multi-purpose adjustable Bench, optimize your workouts!", rating: 5, stats: "The Flat / Incline / Decline Bench is built in the USA, and is a direct descendent of the time-tested Nebula 1080 Utility Bench. This design features an updated spine construction that allows for the connection of a telescoping foot catch assembly. The foot catch locks firmly into place using a pop pin, and sets the user up for movements including the decline bench, decline dumbbell press, and decline sit-ups, among others"},
        {category_id: "5", name: "T-bar Row",  img: "https://www.bestgymequipment.co.uk/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/1/6/16280_tbarrow.jpeg", price: 1200.00, description: "Utilize the T-bar row with close grip and wide grip back rows!", rating: 5, stats: "This fully assembled, no-nonsense machine gives you all the benefits of a neutral-grip T-bar row without the need of a barbell, landmine unit, or other accessories. Compatible with most styles of steel and rubber plates, the T-Bar Row features a 1.88” diameter post with more than a foot of useable length. After loading a desired weight, athletes can establish their proper foot placement on the machine’s 10x20” diamond tread footplates and choose from either the wide or narrow set of easy-grip, knurled handles."},
        {category_id: "5", name: "V-Grip",  img: "https://images-na.ssl-images-amazon.com/images/I/31GjNVK5dxL._SY355_.jpg", price: 60.00, description: "Utilize the V-Grip for all of your Tricep and Bicep needs!", rating: 4, stats: "The handles themselves measure 6 usable handle length and 1.31 in diameter (33MM), and feature our signature black textured powder coat finish for a firm grip. All orders ship with a black carabiner included."},
        {category_id: "5", name: "Arm Blaster",  img: "https://www.ironcompany.com/media/catalog/product/cache/image/1000x1000/af097278c5db4767b0fe9bb92fe21690/c/a/cap-barbell-arm-blaster-front.jpg", price: 45.00, description: "Isolate those biceps with the Arm Blaster!", rating: 5, stats: "The Arm Blaster is another 21st century adaptation of an old-school weightlifting classic. Made from 0.25 thick laser-cut formed aluminum with your choice of a leather or nylon strap, this simple device is designed to be worn around the neck when the lifter is performing biceps curls. By ensuring that the arms remain tight against the body throughout the movement, the Arm Blaster promotes proper form while also isolating the biceps—maximizing the strength-building benefits of the workout"},
        {category_id: "5", name: "Climbing Rope",  img: "https://cdn.shopify.com/s/files/1/0212/8106/products/Knotted-Climbing-Ropes-1_1024x1024.png?v=1441100735", price: 100.00, description: "Build endurance and explosiveness With the FIT Climbing Rope!", rating: 4, stats: "From gym classes to military training to CrossFit, rope climbing exercises have long been a measure of an athlete’s upper body strength and endurance. But if you want to gauge the strength of a climbing rope itself, you need to start with the quality of the materials it’s made from. FIT's American-made manila climbing ropes offer the same reliable grip and durability that’s made the classic manila rope a staple of military bases and shipyards for decades. Available in five different lengths, these gym climbing ropes are designed for indoor/outdoor use with no mounting bracket required"},
        {category_id: "5", name: "Tricep Rope Pulldown",  img: "https://images-na.ssl-images-amazon.com/images/I/71uJ2ZyUjgL._AC_UL320_SR244,320_.jpg", price: 35.00, description: "Kill those triceps with Tricep Rope Pulldowns!", rating: 5, stats: "As far as tricep extension goes, The Rope is the way to go. Utilize the Tricep Extension Rope for maximum contraction in the triceps, with over 20 different variations available to hit the triceps with."},
        {category_id: "6", name: "Sled",  img: "https://www.fitnessdepot.ca/P11UTD8918/assets/ProductImages/CBSLEDPD.jpg?v=1543868097", price: 300.00, description: "Build explosiveness, strength, and endurance with the FIT Sled!", rating: 4, stats: "The CrossFit Games battled-tested Sled comes standard with a quarter-inch steel base plate, 2 x 3 11 inch Gauge and 0.25 Plate Steel, and a pair of 3 upright push bars designed to accommodate both high and low push stances. Compared to many prowler and speed sled designs, the Sled has a smaller overall surface area, allowing you to get the most out of the plates that you own."},
        {category_id: "6", name: "Leg Press",  img: "https://images-na.ssl-images-amazon.com/images/I/81St0dA4VwL._SX425_.jpg", price: 1000.00, description: "Work the Quads and Hamstrings with our Leg Press!", rating: 5, stats: "The Leg Press is suited for athletes of all sizes. This bilateral/unilateral leg press machine has four loadable weight pegs that give it a total weight capacity of up to 2,475LB. It features a pop-pin adjustable lumbar seat and adjustable spring safety stops. Its innovative design also includes a multi-angle foot-deck, linear ball bearings for smooth action and four on-frame weight storage posts."},
        {category_id: "6", name: "Hamstring Curls",  img: "https://lifefitness.com/product-photos/7556/frame_color:6931,second_frame_color:436,upholstery_color:7126/", price: 900.00, description: "Destroy your hamstrings with our FIT Leg Curl Machine!", rating: 4, stats: "FIT's selectorized hamstring unit is designed to help all types of athletes. Manufactured in the USA, the Prone Hamstring Curl Machine features a step-through roller-arm with five adjustable settings for leg length. The body pad is arched at 20 degrees to produce better contraction of the hamstrings than most standard flat pads. And the machine’s 200LB weight stack is conveniently side-mounted to allow for quick and easy weight changes"},
        {category_id: "6", name: "Squat Box",  img: "https://www.elitefts.com/media/catalog/product/cache/1/image/1500x/602f0fa2c1f0d1ba5e241f914e856ff9/b/o/box-squat-box-std_1.jpg", price: 75.00, description: "Break down your Squats with perfect form using our Squat Box!", rating: 5, stats: "The Box Squat allows you to sit back further getting deep into the hams and glutes. It develops the proper squatting muscles while reinforcing correct technique. The wider stance and straighter foot position used for the box squat activates the hips and helps eliminate the excessive (bounce) stretch reflex that many close stance Olympic style lifters get. This makes the box squat more challenging but will also make your regular squat stronger and more efficient."},
        {category_id: "7", name: "12-Sided Urethane Plates",  img: "https://cdn10.bigcommerce.com/s-dk84kd/products/179/images/576/OPHR3_001__84531.1428605333.225.225.jpg?c=2", price: 350.00, description: "Sold in sets of 2, (2.5lb - 45lb).", rating: 5, stats: "FIT's new 12-Sided Urethane Grip Plates feature a solid cast iron core, impact-resistant polyurethane coating, and a black matte finish with white Rogue emblems on each side. Built with two ergonomic interior handles, this unique design allows for easier carrying, loading and offloading, while the not-quite-round circumference helps to prevent rollaway when a barbell's on the floor"},
        {category_id: "7", name: "Metal Olympic Plates",  img: "https://i2.wp.com/www.garagegymreviews.com/wp-content/uploads/2017/05/Rogue-Machined-Olympic-Plates-10-specs.jpg", price: 550.00, description: "Sold in sets of 2, (2.5lb - 45lb).", rating: 5, stats: "Available here in a unique gray hammertone finish with raised black text, FIT's Machined Olympic Plates offer greater precision than many comparable steel plates in the industry. Sold in pairs or as a complete 245LB set, these time-tested cast iron plates range from 2.5LB up to 45LB, with custom orders available to equip your affiliate or home gym as needed"},
        {category_id: "8", name: "Kettle Bells",  img: "https://pimage.sport-thieme.de/detail-fillscale/sport-thieme-kettlebells/219-8008", price: 275.00, description: "Sold in sets (5lb - 70lb)", rating: 5, stats: "FIT's Kettlebells begin as first run iron ore, not scrap, and are formed into a strong, balanced, single-piece casting with a flat wobble-free base. A clean, void-free surface and durable powder-coat finish give FIT Kettlebells an unmatched feel. The FIT Kettlebell was designed around these requirements: Premium Material: We started with the highest quality first run iron ore available, not scrap. Void free surface: We use a proprietary casting process so each bell can reach the highest quality and have the cleanest finish possible. This also allows us to have a smooth, comfortable handle. Single Piece Casting: The FIT Kettlebell is cast in one solid piece, creating a stronger, more reliable handle and a void free surface. The FIT Kettlebell does not use plastic caps, plugs, or patches like lower quality products."},
        {category_id: "8", name: "Resistance Band Pack",  img: "https://cdn.shopify.com/s/files/1/0763/4541/files/Resistance_Loop_Bands_by_Vive_3995d965-a568-462a-a68b-b74970b47a33_large.jpg?v=1520455686", price: 25.00, description: "Sold in packs of 5, resistance based on color.", rating: 4, stats: "The FIT Resistance Bands are a 12 inch version of our standard 41 inch FIT Monster Bands. These have the same color, width and thickness as our standard bands. This length is easier to setup and doesn't require the band to be doubled or tripled over pins or band pegs to get tension."},
        {category_id: "8", name: "Battle Ropes",  img: "http://muscleropes.com/product_images/uploaded_images/muscleropestrio.jpg", price: 125.00, description: "Work the full body, build endurance and explosiveness with Battle Ropes!", rating: 5, stats: "Conditioning Ropes began as a mainstay tool in MMA, and then CrossFit. It is now used by the majority of athletes who train for power and explosiveness. The battling rope is universal because it has an ability to build core strength and improve core-to-extremity strength that helps you to hit your next workout, or opponent, hard."},
        {category_id: "8", name: "Medicine Balls",  img: "http://www.totalstrengthandspeed.com/content/images/thumbs/0000316_ultrafit-demolition-medicine-balls-14.jpeg", price: 100.00, description: "Enjoy full body explosive workouts with our Medicine Balls!", rating: 5, stats: "Customers can choose from 11 different weight increments—ranging from 4LB up to 30LB—all featuring the same 14 inch diameter and scuff-resistant vinyl shell for a consistent feel as you progress. The interior filling is substantial enough to help the ball keep its shape over repeated use, but forgiving enough for athletes to safely stop or catch the ball at high velocity."}
      ]);
    });
};
